# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'apham'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-91332049-1'

menu:
  - name: 首页
    link: /
  - name: 存档
    link: /archive.thml
  - name: 关于我
    link: /aboutus.html
